# Unets
use_boss: 0
#Boss files
img_file:
  class: File
  path: kasthuri/kasthuri_raw.npy
lbl_file:
  class: File
  path: kasthuri/kasthuri_syn_gt.npy
train_pct: 0.85
n_epochs: 20
mb_size: 4
n_mb_per_epoch: 3
learning_rate: 0.001
beta1: 0.9
beta2: 0.999
save_freq: 50
use_adam: True
do_warp: False
tile_size: 256
output: kasthuri_weights.h5
score_out: f1_kasthuri.npy
